version: 2.1
orbs:
  slack: circleci/slack@4.5.0

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout  

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Unit Tests
          command: npm test

      - run:
          name: Generate Code Coverage
          command: npm run coverage

      - store_artifacts:
          path: coverage-report 

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build

    post-steps:
      - slack/notify:
          event: warning
          channel: general
          message: "This is Nicolas Petrick submitting the Slack assignment"

