version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest # Set up a Node.js executor
    steps:
      - checkout  # Checkout the repository code

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install 

      - run:
          name: Run Unit Tests
          command: npm test 

      - run:
          name: Generate Code Coverage Report
          command: npm run coverage 

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - store_artifacts:
          path: coverage-report  
          
workflows:
  version: 2
  build_and_notify:
    jobs:
      - build

    post-steps:
      - slack/notify:
          event: warning
          channel: general
          message: "This is Nicolas Petrick submitting the Slack assignment"
