version: 2.1
orbs:
  slack: circleci/slack@4.12.5

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: "#general"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "This is Nicolas Petrick submitting the Slack assignment.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
          
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout  

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Unit Tests
          command: npm test

      - run:
          name: Generate Code Coverage
          command: npm run test:coverage

      - store_artifacts:
          path: coverage-report 

workflows:
  send-notification:
    jobs:
      - build
      - notify

